import b1 from "./boatimages/b1.jpg"
import b2 from "./boatimages/b2.jpg"
import b3 from "./boatimages/b3.jpg"
import b4 from "./boatimages/b4.jpg"
import b5 from "./boatimages/b5.jpg"
import b6 from "./boatimages/b6.jpg"
import b7 from "./boatimages/b7.jpg"
import b8 from "./boatimages/b8.jpg"

export const Boatdata=[
    {img:b1,
     bname:"boAt Rockerz 558",
     price:"₹ 1,999",
     oprice:"₹4,999",
     discount:"60% off",
     order:"ORDER",
     cart:"ADD TO CART",
     q:0,
      },
    {img:b2,
     bname:"boAt Nirvana 751 ",
     price:"₹ 3,999",
     oprice:"₹ 7,999",
     discount:"50% off",
     order:"ORDER",
     cart:"ADD TO CART",
     q:0,
      },
    {img:b3,
     bname:"boAt Airdopes 190",
     price:" ₹ 1,299",
     oprice:" ₹ 3,490",
     discount:"63% off",
     order:"ORDER",
     cart:"ADD TO CART",
     q:0,
      },
    {img:b4,
     bname:"boAt Airdopes 141",
     price:"₹ 1,199",
     oprice:"₹4,999",
     discount:"73% off",
     order:"ORDER",
     cart:"ADD TO CART",
     q:0,
      },
    {img:b5,
     bname:"Rockerz 245 v2 Pro",
     price:"₹ 999",
     oprice:"₹3,999",
     discount:"73% off",
     order:"ORDER",
     cart:"ADD TO CART",
     q:0,
      },
    {img:b6,
     bname:"boAt Rockerz 330 pro",
     price:"₹ 1,499",
     oprice:"₹2,999",
     discount:"50% off",
     order:"ORDER",
     cart:"ADD TO CART",
     q:0,
      },
    {img:b7,
     bname:"boAt Bassheads 242",
     price:"₹ 599",
     oprice:"₹1,490",
     discount:"60% off",
     order:"ORDER",
     cart:"ADD TO CART",
     q:0,
      },
    {img:b8,
     bname:"boAt BassHeads 122",
     price:"₹ 375",
     oprice:"₹1,299",
     discount:"71% off",
     order:"ORDER",
     cart:"ADD TO CART",
     q:0,
      },
]