import u1 from "./ubl images/u1.jpg"

export const Jbldata=[
    {
        img:u1,
        bname:"JBL Jr310BT",
        price:"₹3,314",
        oprice:"₹4,144",
        discount:"20% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
    },
    {
        img:u1,
        bname:"JBL Jr310BT",
        price:"₹3,314",
        oprice:"₹4,144",
        discount:"20% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
    },
    {
        img:u1,
        bname:"JBL Jr310BT",
        price:"₹3,314",
        oprice:"₹4,144",
        discount:"20% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
    },
    {
        img:u1,
        bname:"JBL Jr310BT",
        price:"₹3,314",
        oprice:"₹4,144",
        discount:"20% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
    },
    {
        img:u1,
        bname:"JBL Jr310BT",
        price:"₹3,314",
        oprice:"₹4,144",
        discount:"20% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
    },
    {
        img:u1,
        bname:"JBL Jr310BT",
        price:"₹3,314",
        oprice:"₹4,144",
        discount:"20% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
    },
    {
        img:u1,
        bname:"JBL Jr310BT",
        price:"₹3,314",
        oprice:"₹4,144",
        discount:"20% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
    },
    {
        img:u1,
        bname:"JBL Jr310BT",
        price:"₹3,314",
        oprice:"₹4,144",
        discount:"20% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
    },
]