import s1 from "./skullcandyimages/s1.jpg"

export const Skullcandydata=[
    {img:s1,
        bname:"SLYR® Pro",
        price:"₹ 28,999",
        oprice:"₹ 32,000",
        discount:"40% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
     },
    {img:s1,
        bname:"SLYR® Pro",
        price:"₹ 28,999",
        oprice:"₹ 32,000",
        discount:"40% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
     },
    {img:s1,
        bname:"SLYR® Pro",
        price:"₹ 28,999",
        oprice:"₹ 32,000",
        discount:"40% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
     },
    {img:s1,
        bname:"SLYR® Pro",
        price:"₹ 28,999",
        oprice:"₹ 32,000",
        discount:"40% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
     },
    {img:s1,
        bname:"SLYR® Pro",
        price:"₹ 28,999",
        oprice:"₹ 32,000",
        discount:"40% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
     },
    {img:s1,
        bname:"SLYR® Pro",
        price:"₹ 28,999",
        oprice:"₹ 32,000",
        discount:"40% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
     },
    {img:s1,
        bname:"SLYR® Pro",
        price:"₹ 28,999",
        oprice:"₹ 32,000",
        discount:"40% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
     },
    {img:s1,
        bname:"SLYR®pro",
        price:"₹ 28,999",
        oprice:"₹ 32,000",
        discount:"40% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
     },
]