import sony1 from "./sonyimages/sony1.jpg"

export const Sonydata=[
    {
        img:sony1,
        bname:"Sony WH-CH520",
        price:"₹5,470",
        oprice:"₹5,990",
        discount:"9% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
},
    {
        img:sony1,
        bname:"Sony WH-CH520",
        price:"₹5,470",
        oprice:"₹5,990",
        discount:"9% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
},
    {
        img:sony1,
        bname:"Sony WH-CH520",
        price:"₹5,470",
        oprice:"₹5,990",
        discount:"9% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
},
    {
        img:sony1,
        bname:"Sony WH-CH520",
        price:"₹5,470",
        oprice:"₹5,990",
        discount:"9% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
},
    {
        img:sony1,
        bname:"Sony WH-CH520",
        price:"₹5,470",
        oprice:"₹5,990",
        discount:"9% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
},
    {
        img:sony1,
        bname:"Sony WH-CH520",
        price:"₹5,470",
        oprice:"₹5,990",
        discount:"9% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
},
    {
        img:sony1,
        bname:"Sony WH-CH520",
        price:"₹5,470",
        oprice:"₹5,990",
        discount:"9% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
},
    {
        img:sony1,
        bname:"Sony WH-CH520",
        price:"₹5,470",
        oprice:"₹5,990",
        discount:"9% off",
        order:"ORDER",
        cart:"ADD TO CART",
        q:0,
},
]